# Promega Organoid Analysis Pipeline Makefile
# ===========================================
# This Makefile automates the 18-step preprocessing and classification pipeline
# documented in README.md
#
# Quick Start:
#   make help              - Show all available targets
#   make pipeline-all      - Run complete preprocessing pipeline (Steps 1-16)
#   make train-all         - Train both classifiers (Steps 17-18)
#
# Environment Variables:
#   DATA_ROOT             - Root data directory (default: /net/projects2/promega/2026_04_15_data)
#                           Contains: raw/, intermediate/, models/, analysis_output/
#   PYTHON                - Python executable (default: conda run -n core_env python3)
#   PYTHON_MMCV           - Python with mmcv env (default: conda run -n mmcv_env python)
#   MMCV_ENV_PATH         - Path to mmcv conda env (default: $(HOME)/miniconda3/envs/mmcv_env)

# -------- Configuration --------
DATA_ROOT          ?= /net/projects2/promega/2026_04_15_data
RAW_DIR            ?= $(DATA_ROOT)/raw
INTERMEDIATE_DIR   ?= $(DATA_ROOT)/intermediate
MODELS_DIR         ?= $(DATA_ROOT)/models
# Analysis outputs (figures, results JSON/CSV) go to a single repo-local
# directory that is gitignored (.gitignore: analysis_output/), NOT under
# DATA_ROOT (/net). This matches the data_loader default so `make run` and a
# direct `python ...` write to the same place. Override with
# `make run ANALYSIS_OUTPUT_DIR=/some/path ...` if needed.
ANALYSIS_OUTPUT_DIR ?= $(CURDIR)/analysis_output
PYTHON             ?= conda run --no-capture-output -n core_env python3
MMCV_ENV_PATH      ?= $(HOME)/miniconda3/envs/mmcv_env
PYTHON_MMCV        ?= conda run --no-capture-output -p $(MMCV_ENV_PATH) python
PYTHONPATH         := $(shell pwd)

# CUDA env for mmcv steps — use the conda env's bundled CUDA 11.3 (cudatoolkit-dev=11.3.1)
# so mmcv's build/runtime finds the matching CUDA toolchain instead of system CUDA 12.x.
MMCV_ENV_PREFIX    := CUDA_HOME=$(MMCV_ENV_PATH) LD_LIBRARY_PATH=$(MMCV_ENV_PATH)/lib:$$LD_LIBRARY_PATH PATH=$(MMCV_ENV_PATH)/bin:$$PATH

# Raw input files (never written by pipeline)
IMAGE_VERIFICATION_CSV := $(RAW_DIR)/image_verification.csv
SAMPLE_TRACING_XLSX    := $(RAW_DIR)/Sample-Tracing.xlsx
RAW_IMAGES_DIR         := $(RAW_DIR)/images/raw_images
MANUAL_MASKS_DIR       := $(RAW_DIR)/masks/manual
METABOLITE_XLSX        := $(RAW_DIR)/metabolite.xlsx
SURVEY_DIR             := $(RAW_DIR)/surveys

# In-repo normalized metabolite source (Promega residualized output)
NORMALIZED_METABOLITES_CSV := data/normalized/CONC_data_organoides_residualized_final.csv

# Intermediate directories (regenerated by make pipeline-all)
INDEXES_DIR        := $(INTERMEDIATE_DIR)/indexes
RESIZED_DIR        := $(INTERMEDIATE_DIR)/resized_512x384
SPLITS_DIR         := $(INTERMEDIATE_DIR)/resized_512x384_splits
OVERLAYS_DIR       := $(INTERMEDIATE_DIR)/overlays
RESIZED_575_DIR    := $(INTERMEDIATE_DIR)/resized_575_square
RESIZED_575_MASKS  := $(INTERMEDIATE_DIR)/resized_575_square_masks
MEANFILL_DIR       := $(INTERMEDIATE_DIR)/mean_fill_clip
FILTER_DIR         := $(INTERMEDIATE_DIR)/filter_complete_series
LSTM_DIR           := $(INTERMEDIATE_DIR)/lstm_ready
MASKS_PROCESSED    := $(INTERMEDIATE_DIR)/masks_processed

# Model output directories (regenerated by make train-all)
MMSEG_DIR          := $(MODELS_DIR)/mmseg
IMGQUAL_DIR        := $(MODELS_DIR)/imagequality_classification
IMGSURVEY_DIR      := $(MODELS_DIR)/image_survey_classification

# Intermediate index files
RECORD_IDENTIFIERS     := $(INDEXES_DIR)/record_identifiers.json
METABOLITE_MAP         := $(INDEXES_DIR)/metabolite_map.json
SURVEY_MAP             := $(INDEXES_DIR)/survey_map.json
IMAGE_MAP              := $(INDEXES_DIR)/image_map.json
IMAGE_MAP_MANUAL       := $(INDEXES_DIR)/image_mapping_thresholded_and_manual.json
IMAGE_MAP_RESIZED      := $(INDEXES_DIR)/image_map_resized_512x384.json
IMAGE_MAP_PREDICTED    := $(INDEXES_DIR)/image_map_resized_512x384_predicted.json
IMAGE_MAP_OVERLAY      := $(INDEXES_DIR)/image_map_resized_512x384_predicted_overlay.json
IMAGE_MAP_MEANFILL     := $(INDEXES_DIR)/image_map_resized_512x384_predicted_overlay_ar.json
IMAGE_MAP_MERGE        := $(INDEXES_DIR)/image_map_resized_512x384_predicted_overlay_ar_meanfill.json
ALL_DATA_JSON          := data/all_data.json
SPLITS_CSV             := data/splits/canonical_2026_winter.csv
IMAGE_CLASSIFIER_JSON  := $(IMGQUAL_DIR)/image_classifier.json
SURVEY_CLASSIFIER_JSON := $(IMGSURVEY_DIR)/survey_classifier.json

# Options
# OVERWRITE: defaults to 1 (regenerate). Pass OVERWRITE= to enable incremental skip-on-exists.
OVERWRITE          ?= 1
TARGET_WIDTH       ?= 512
TARGET_HEIGHT      ?= 384
MIN_SURVEY_VOTES   ?= 4
TRAIN_FRAC         ?= 0.8
VAL_FRAC           ?= 0.1

# Step 17 sweep toggles (replaces former analysis/imagequality_classification/run_*mask*.s scripts)
INPUT_KEY          ?= img_path     # img_path | overlay_path
USE_MASK           ?=              # set to anything truthy to enable --use-mask

# Segmentation training (early vs late datasets)
SEG_TRAIN_SCRIPT ?= pipeline/images/segmentation_mmseg/train.py
SEG_CONFIG       ?= pipeline/images/segmentation_mmseg/segformer_mitb0.py
SEG_WORK_ROOT    ?= $(MMSEG_DIR)
GPU              ?=
RESUME           ?=

# Segmentation models (outputs from step8)
# Each training run writes into its own timestamped dir that contains both the
# config snapshot and the checkpoints: $(SEG_WORK_ROOT)/<phase>/YYYYMMDD_HHMMSS/
EARLY_RUN_DIR    = $(shell ls -t $(SEG_WORK_ROOT)/early/ 2>/dev/null | grep -E '^[0-9]{8}_[0-9]{6}$$' | head -1)
LATE_RUN_DIR     = $(shell ls -t $(SEG_WORK_ROOT)/late/ 2>/dev/null | grep -E '^[0-9]{8}_[0-9]{6}$$' | head -1)
EARLY_CONFIG     ?= $(SEG_WORK_ROOT)/early/$(EARLY_RUN_DIR)/config.py
EARLY_CHECKPOINT ?= $(SEG_WORK_ROOT)/early/$(EARLY_RUN_DIR)/iter_1000.pth
LATE_CONFIG      ?= $(SEG_WORK_ROOT)/late/$(LATE_RUN_DIR)/config.py
LATE_CHECKPOINT  ?= $(SEG_WORK_ROOT)/late/$(LATE_RUN_DIR)/iter_1000.pth


# Classifier training options
EPOCH1             ?= 100
EPOCH2             ?= 300
BATCH_SIZE         ?= 16
DETERMINISTIC      ?= 1
SEED               ?= 1

# -------- Phony Targets --------
.PHONY: help clean run \
        step1 step2 step3 step4 step5 step6 step7 step8 step9 step10 \
        step11 step12 step13 step14 step15 step16 step17 step18 \
        imagequality-classification image-survey-classification \
        pipeline-identifiers pipeline-mappers pipeline-preprocessing \
        pipeline-segmentation pipeline-quality pipeline-series \
        pipeline-merge pipeline-all train-all \
        validate-inputs

# -------- Generic Python runner --------
# Usage: make run ARGS="-m analysis.generate_splits --dry-run"
#        make run ARGS="scripts/my_script.py --flag value"
ARGS ?=
run:
	PYTHONPATH=$(PYTHONPATH) ANALYSIS_OUTPUT_DIR=$(ANALYSIS_OUTPUT_DIR) $(PYTHON) $(ARGS)

# -------- Provenance checks (assert our computed values match Promega's) --------
.PHONY: verify-winsorize verify-mask-area verify-metabolites
# Assert our per-day 1/99 winsorization reproduces the stored `win` columns
# (5 metabolites within tolerance; MalateGlo is the documented exception).
verify-winsorize:
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.metabolites.winsorize --all-data $(ALL_DATA_JSON)

# Assert our segmentation-derived mask_area_um2 reproduces the lab's Area_win.
verify-mask-area:
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.images.quality.organoid_area \
		--all-data $(ALL_DATA_JSON)

verify-metabolites: verify-winsorize verify-mask-area

.PHONY: seg-train-early seg-train-late

seg-train-early: validate-mmcv-env
	PYTHONPATH=$(PYTHONPATH) $(MMCV_ENV_PREFIX) $(PYTHON_MMCV) $(SEG_TRAIN_SCRIPT) \
		--config $(SEG_CONFIG) \
		--splits-dir $(SPLITS_DIR) \
		--split early \
		--work-dir $(SEG_WORK_ROOT)/early \
		$(if $(RESUME),--resume) \
		$(if $(GPU),--cfg-options launcher=pytorch gpu_ids=$(GPU))

seg-train-late: validate-mmcv-env
	PYTHONPATH=$(PYTHONPATH) $(MMCV_ENV_PREFIX) $(PYTHON_MMCV) $(SEG_TRAIN_SCRIPT) \
		--config $(SEG_CONFIG) \
		--splits-dir $(SPLITS_DIR) \
		--split late \
		--work-dir $(SEG_WORK_ROOT)/late \
		$(if $(RESUME),--resume) \
		$(if $(GPU),--cfg-options launcher=pytorch gpu_ids=$(GPU))


# -------- Help --------
help:
	@echo "=================================="
	@echo "Promega Pipeline Makefile"
	@echo "=================================="
	@echo ""
	@echo "QUICK START:"
	@echo "  make pipeline-all          - Run complete preprocessing pipeline (Steps 1-16)"
	@echo "  make train-all             - Train both classifiers (Steps 17-18)"
	@echo ""
	@echo "PIPELINE SECTIONS:"
	@echo "  make pipeline-identifiers  - Step 1: Retrieve identifiers"
	@echo "  make pipeline-mappers      - Steps 2-4: Map metabolite, survey, image data"
	@echo "  make pipeline-preprocessing - Steps 5-7: Manual masks, resize, test splits"
	@echo "  make pipeline-segmentation - Steps 8-9: Train and predict segmentation"
	@echo "  make pipeline-quality      - Steps 10-11: Overlays and edge fraction"
	@echo "  make pipeline-series       - Steps 12-15: Filter series, LSTM prep, resize"
	@echo "  make pipeline-merge        - Step 16: Generate all_data.json"
	@echo ""
	@echo "INDIVIDUAL STEPS:"
	@echo "  make step1                 - Retrieve main identifiers"
	@echo "  make step2                 - Map metabolite data"
	@echo "  make step3                 - Map survey data"
	@echo "  make step4                 - Map image data"
	@echo "  make step5                 - Map manual masks"
	@echo "  make step6                 - Resize and remap images"
	@echo "  make step7                 - Create test splits"
	@echo "  make step8                 - Train segmentation model"
	@echo "  make step9                 - Predict segmentation masks"
	@echo "  make step10                - Create image-mask overlays"
	@echo "  make step11                - Calculate mask edge fraction"
	@echo "  make step12                - Filter complete series"
	@echo "  make step13                - Preprocess for LSTM"
	@echo "  make step14                - Resize with aspect ratio"
	@echo "  make step15                - Mean fill clip"
	@echo "  make step16                - Generate all_data.json"
	@echo "  make step17                - Train image quality classifier (alias: imagequality-classification)"
	@echo "  make step18                - Train image survey classifier (alias: image-survey-classification)"
	@echo ""
	@echo "ANALYSIS RUNNERS (non-canonical experiments / paper repro):"
	@echo "  make analysis-train-dinov2          - Train DINOv2 image classifier (fixed splits)"
	@echo "  make analysis-multimodal            - Multimodal classifier (single config; set BACKBONE/FUSION/INPUT_MODE)"
	@echo "  make analysis-paper-perday         - Per-day image study (paper Fig 7-9)"
	@echo "  make analysis-batch-summary        - BA1/BA2 dataset summary table (descriptive stats)"
	@echo "  make analysis-verify-idor          - Verify partner IDOR organoid list against all_data.json"
	@echo ""
	@echo "CONFIGURATION:"
	@echo "  DATA_ROOT=$(DATA_ROOT)"
	@echo "  RAW_DIR=$(RAW_DIR)"
	@echo "  INTERMEDIATE_DIR=$(INTERMEDIATE_DIR)"
	@echo "  MODELS_DIR=$(MODELS_DIR)"
	@echo "  OVERWRITE=$(OVERWRITE)"
	@echo "  TARGET_WIDTH=$(TARGET_WIDTH), TARGET_HEIGHT=$(TARGET_HEIGHT)"
	@echo ""
	@echo "GENERAL:"
	@echo "  make run ARGS='...'             - Run any Python command in conda env"
	@echo ""
	@echo "EXAMPLES:"
	@echo "  make run ARGS='-m analysis.paper_2026_04.generate_splits --dry-run'"
	@echo "  make step1 DATA_ROOT=/path/to/data"
	@echo "  make step6 OVERWRITE=        # incremental: skip outputs that already exist"
	@echo "  make pipeline-all OVERWRITE= # incremental whole pipeline"
	@echo "  make step17 EPOCH1=50 EPOCH2=150 DETERMINISTIC=1"
	@echo ""

# ====================================
# STEP 1: Retrieve Main Identifiers
# ====================================
step1: validate-inputs
	@echo "===> STEP 1: Retrieving main identifiers"
	@mkdir -p $(INDEXES_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.identifiers.retrieve_main_identifiers \
		--csv-file $(IMAGE_VERIFICATION_CSV) \
		--out-file $(RECORD_IDENTIFIERS)
	@echo "===> Output: $(RECORD_IDENTIFIERS)"

# ====================================
# STEP 2: Map Metabolite Data
# ====================================
step2: $(RECORD_IDENTIFIERS) $(NORMALIZED_METABOLITES_CSV)
	@echo "===> STEP 2: Mapping metabolite data"
	@mkdir -p $(INDEXES_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.metabolites.metabolite_mapper \
		--in-file $(METABOLITE_XLSX) \
		--identifiers $(RECORD_IDENTIFIERS) \
		--out-file $(METABOLITE_MAP) \
		--normalized-csv $(NORMALIZED_METABOLITES_CSV)
	@echo "===> Output: $(METABOLITE_MAP)"

# ====================================
# STEP 3: Map Survey Data
# ====================================
step3: $(RECORD_IDENTIFIERS)
	@echo "===> STEP 3: Mapping survey data"
	@mkdir -p $(INDEXES_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.surveys.surveys_mapper \
		--in-dir $(SURVEY_DIR) \
		--out-file $(SURVEY_MAP) \
		--identifiers $(RECORD_IDENTIFIERS) \
		--min-survey-votes $(MIN_SURVEY_VOTES)
	@echo "===> Output: $(SURVEY_MAP)"

# ====================================
# STEP 4: Map Image Data
# ====================================
step4: $(RECORD_IDENTIFIERS)
	@echo "===> STEP 4: Mapping image data"
	@mkdir -p $(INDEXES_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.images.image_mapper \
		--base-dir $(RAW_IMAGES_DIR) \
		--verify-csv $(IMAGE_VERIFICATION_CSV) \
		--meta-xlsx $(SAMPLE_TRACING_XLSX) \
		--identifiers $(RECORD_IDENTIFIERS) \
		--out-file $(IMAGE_MAP)
	@echo "===> Output: $(IMAGE_MAP)"

# ====================================
# STEP 5: Map Manual Masks & Resize
# ====================================
step5: $(IMAGE_MAP)
	@echo "===> STEP 5: Mapping + preprocessing manual masks"
	@mkdir -p $(MASKS_PROCESSED)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.images.segmentation_mmseg.preprocessing.manual_masks_mapping \
		--image-json $(IMAGE_MAP) \
		--masks-dir $(MANUAL_MASKS_DIR) \
		--output-file $(IMAGE_MAP_MANUAL) \
		--target-width $(TARGET_WIDTH) \
		--target-height $(TARGET_HEIGHT) \
		--processed-masks-dir $(MASKS_PROCESSED)/manual_processed_$(TARGET_WIDTH)x$(TARGET_HEIGHT) \
		$(if $(OVERWRITE),--overwrite)


# ====================================
# STEP 6: Resize and Remap Images
# ====================================
step6: $(IMAGE_MAP) $(IMAGE_MAP_MANUAL)
	@echo "===> STEP 6: Resizing and remapping images"
	@mkdir -p $(RESIZED_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.images.resize.resize_remap_images \
		--image-mapping-json $(IMAGE_MAP) \
		--mask-mapping-json $(IMAGE_MAP_MANUAL) \
		--out-dir $(RESIZED_DIR) \
		--out-mapping-json $(IMAGE_MAP_RESIZED) \
		--target-width $(TARGET_WIDTH) \
		--target-height $(TARGET_HEIGHT) \
		$(if $(OVERWRITE),--overwrite)
	@echo "===> Output: $(IMAGE_MAP_RESIZED)"

# ====================================
# STEP 7: Create Test Splits
# ====================================
step7: $(IMAGE_MAP_RESIZED)
	@echo "===> STEP 7: Creating test splits"
	@mkdir -p $(SPLITS_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.images.segmentation_mmseg.preprocessing.test_split \
		--resized-json $(IMAGE_MAP_RESIZED) \
		--splits-dir $(SPLITS_DIR) \
		--train-frac $(TRAIN_FRAC) \
		--val-frac $(VAL_FRAC) \
		--split-days
	@echo "===> Output: $(SPLITS_DIR)/"

# ====================================
# STEP 8: Train Segmentation Model
# ====================================
# Default phase for segmentation steps (early or late)
PHASE ?= late

step8: step7
	@echo "===> STEP 8: Training segmentation model (PHASE=$(PHASE))"
	$(MAKE) seg-train-$(PHASE) GPU=$(GPU) RESUME=$(RESUME)



# ====================================
# STEP 9: Predict Segmentation Masks
# ====================================
# Note: Requires checkpoint from step8
# Choose correct model files based on PHASE
ifeq ($(PHASE),early)
  CONFIG_FILE = $(EARLY_CONFIG)
  CHECKPOINT  = $(EARLY_CHECKPOINT)
else ifeq ($(PHASE),late)
  CONFIG_FILE = $(LATE_CONFIG)
  CHECKPOINT  = $(LATE_CHECKPOINT)
else
  $(error PHASE must be early or late)
endif

# Which mapping JSON to run inference on (defaults to resized)
PRED_INPUT_JSON ?= $(IMAGE_MAP_RESIZED)

step9: validate-mmcv-env
	@echo "===> STEP 9: Predicting segmentation masks (PHASE=$(PHASE))"
	@mkdir -p $(MMSEG_DIR)/predicted
	@if [ ! -f "$(CHECKPOINT)" ]; then \
		echo "ERROR: Checkpoint not found: $(CHECKPOINT)"; \
		exit 1; \
	fi
	PYTHONPATH=$(PYTHONPATH) $(MMCV_ENV_PREFIX) $(PYTHON_MMCV) -m pipeline.images.segmentation_mmseg.predict_masks \
		--image-mapping-json $(PRED_INPUT_JSON) \
		--out-dir $(MMSEG_DIR)/predicted \
		--model-type $(PHASE) \
		--config $(CONFIG_FILE) \
		--checkpoint $(CHECKPOINT) \
		$(if $(DAYS),--days $(DAYS)) \
		--write-collage \
		$(if $(OVERWRITE),--overwrite)
	@echo "===> Output masks: $(MMSEG_DIR)/predicted/"

step9-early:
	$(MAKE) step9 PHASE=early OVERWRITE=$(OVERWRITE) DAYS=Dy03,Dy06,Dy08,Dy10 PRED_INPUT_JSON=$(IMAGE_MAP_RESIZED)

step9-late:
	$(MAKE) step9 PHASE=late OVERWRITE=$(OVERWRITE) DAYS=Dy13,Dy15,Dy17,Dy20,Dy21,Dy24,Dy28,Dy30 \
	  PRED_INPUT_JSON=$(IMAGE_MAP_RESIZED:.json=_predicted.json)
	@# predict_masks.py hardcodes output to <input_stem>_predicted.json, so
	@# feeding it the early-output JSON produces _predicted_predicted.json.
	@# Collapse that back to the canonical _predicted.json for step10.
	@mv $(IMAGE_MAP_RESIZED:.json=_predicted_predicted.json) $(IMAGE_MAP_PREDICTED)


# ====================================
# STEP 10: Create Image-Mask Overlays
# ====================================
# Uses predicted mapping (step9 output): overlays need both processed_image and predicted_mask_path
step10: $(IMAGE_MAP_PREDICTED)
	@echo "===> STEP 10: Creating image-mask overlays"
	@mkdir -p $(OVERLAYS_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.images.quality.image_mask_overlay \
		--image-mapping-json $(IMAGE_MAP_PREDICTED) \
		--overlay-dir $(OVERLAYS_DIR) \
		$(if $(OVERWRITE),--overwrite)
	@echo "===> Output: $(OVERLAYS_DIR)/"

# ====================================
# STEP 11: Calculate Mask Edge Fraction
# ====================================
# Uses overlay mapping (step10 output): has predicted_mask_path and overlay_path
step11: step10
	@echo "===> STEP 11: Calculating mask edge fraction"
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.images.quality.mask_edge_fraction \
		--image-mapping-json $(IMAGE_MAP_OVERLAY)
	@echo "===> Updated: $(IMAGE_MAP_OVERLAY) (with edge_fraction field)"

# ====================================
# STEP 12: Filter Complete Series
# ====================================
step12: $(IMAGE_MAP_PREDICTED)
	@echo "===> STEP 12: Filtering complete series"
	@mkdir -p $(FILTER_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.images.series.filter_complete_series \
		--image-mapping-json $(IMAGE_MAP_PREDICTED) \
		--out-dir $(FILTER_DIR) \
		--show-examples
	@echo "===> Output: $(FILTER_DIR)/"

# ====================================
# STEP 13: Preprocess for LSTM
# ====================================
step13: step12
	@echo "===> STEP 13: Preprocessing for LSTM"
	@mkdir -p $(LSTM_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.images.series.preprocess_for_lstm \
		--complete-series $(FILTER_DIR)/complete_series_data_no_blanks.json \
		--raw-image-dir $(RAW_IMAGES_DIR) \
		--out-dir $(LSTM_DIR)
	@echo "===> Output: $(LSTM_DIR)/"

# ====================================
# STEP 14: Resize with Aspect Ratio
# ====================================
# Uses overlay mapping (step10+11) so output has overlay+edge+ar; step15 consumes this
step14: step11
	@echo "===> STEP 14: Resizing with aspect ratio"
	@mkdir -p $(RESIZED_575_DIR)
	@mkdir -p $(RESIZED_575_MASKS)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.images.resize.resize_aspect_ratio \
		--image-mapping-json $(IMAGE_MAP_OVERLAY) \
		--raw-images-dir $(RAW_IMAGES_DIR) \
		--out-images-dir $(RESIZED_575_DIR) \
		--out-masks-dir $(RESIZED_575_MASKS) \
		--require-mask \
		$(if $(OVERWRITE),--overwrite)
	@echo "===> Output: $(RESIZED_575_DIR)/"
	@echo "===> Output: $(IMAGE_MAP_MEANFILL)"

# ====================================
# STEP 15: Mean Fill Clip
# ====================================
# Uses IMAGE_MAP_MEANFILL produced by step14 (overlay_ar.json)
step15: step14
	@echo "===> STEP 15: Applying mean fill clip"
	@mkdir -p $(MEANFILL_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.images.postprocess.meanfill_clip \
		--image-mapping-json $(IMAGE_MAP_MEANFILL) \
		--compute-mean \
		--save-computed-mean \
		--out-images-dir $(MEANFILL_DIR) \
		--images-base $(RESIZED_575_DIR) \
		--masks-base $(RESIZED_575_MASKS) \
		--require-mask \
		$(if $(OVERWRITE),--overwrite)
	@echo "===> Output: $(MEANFILL_DIR)/"

# ====================================
# STEP 16: Generate All Data JSON
# ====================================
step16: $(METABOLITE_MAP) $(SURVEY_MAP) $(IMAGE_MAP_MERGE)
	@echo "===> STEP 16: Generating all_data.json"
	@mkdir -p data
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.merge.merge_all_data \
		--data-dir $(DATA_ROOT) \
		--image-mapping-json $(IMAGE_MAP_MERGE) \
		--min-survey-votes $(MIN_SURVEY_VOTES) \
		--target-width $(TARGET_WIDTH) \
		--target-height $(TARGET_HEIGHT) \
		--out-file $(ALL_DATA_JSON)
	@echo "===> Output: $(ALL_DATA_JSON)"

# ====================================
# STEP 16b: Winsorize metabolites into all_data.json
# ====================================
# Adds per-day 1st/99th-percentile-clipped <field>_win columns
# (concentration_uM_win, initial_concentration_win) computed from the raw
# values -- the same per-day winsorization asserted by `make verify-winsorize`.
# Runs after step16 and rewrites all_data.json in place; part of pipeline-merge.
.PHONY: winsorize-write
winsorize-write: step16
	@echo "===> STEP 16b: Winsorizing metabolites into all_data.json"
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pipeline.metabolites.winsorize \
		--write --all-data $(ALL_DATA_JSON)
	@echo "===> Output: $(ALL_DATA_JSON) (with *_win columns)"

# ====================================
# STEP 17: Image Quality Classification
# ====================================
step17 imagequality-classification: step16
	@echo "===> STEP 17: Training image quality classifier (input=$(INPUT_KEY), use_mask=$(if $(USE_MASK),yes,no))"
	@mkdir -p $(IMGQUAL_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m analysis.imagequality_classification.train_model_accuracy \
		--data-dir $(DATA_ROOT) \
		--image-classifier-json $(IMAGE_CLASSIFIER_JSON) \
		--all-data-json $(ALL_DATA_JSON) \
		--epoch1 $(EPOCH1) \
		--epoch2 $(EPOCH2) \
		--batch-size $(BATCH_SIZE) \
		--test-frac 0.1 \
		--val-frac 0.1 \
		--input-path-key $(INPUT_KEY) \
		$(if $(USE_MASK),--use-mask) \
		$(if $(DETERMINISTIC),--deterministic) \
		--seed $(SEED)
	@echo "===> Output: $(IMGQUAL_DIR)/"

# ====================================
# STEP 18: Image Survey Classification
# ====================================
step18 image-survey-classification: step16
	@echo "===> STEP 18: Training image survey classifier"
	@mkdir -p $(IMGSURVEY_DIR)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m analysis.image_survey_classification.simple_classifier \
		--data-dir $(DATA_ROOT) \
		--survey-classifier-json $(SURVEY_CLASSIFIER_JSON) \
		--all-data-json $(ALL_DATA_JSON) \
		--batch-size 8 \
		--epoch1 50 \
		--epoch2 150 \
		$(if $(DETERMINISTIC),--deterministic) \
		--seed $(SEED)
	@echo "===> Output: $(IMGSURVEY_DIR)/"

# ====================================
# ANALYSIS RUNNERS (non-canonical experiments and paper replication)
# ====================================
# Reserved naming: stepN = canonical pipeline (1-18). Analysis runners use the
# `analysis-` prefix and live outside the numbered sequence.

# DINOv2 image-quality classifier (fixed-splits experiment).
analysis-train-dinov2:
	@echo "===> Training DINOv2 image classifier (fixed splits)"
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m analysis.imagequality_classification.train_model_dinov2 \
		--all-data $(ALL_DATA_JSON) \
		--splits-csv $(SPLITS_CSV) \
		--mode base \
		--batch-size 16 \
		--val-batch-size 16 \
		--input-path-key img_path \
		--outdir $(MODELS_DIR)/imagequality_classification/dinov2_fixed_splits

# Multimodal classifier — single configuration.
# Override BACKBONE / FUSION / INPUT_MODE per call (defaults match the array sweep below).
BACKBONE   ?= resnet
FUSION     ?= concat
INPUT_MODE ?= rgb
analysis-multimodal:
	@echo "===> Multimodal training: backbone=$(BACKBONE) fusion=$(FUSION) input=$(INPUT_MODE)"
	@mkdir -p analysis/multimodal/outputs_multimodal/$(BACKBONE)_$(INPUT_MODE)_$(FUSION)
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m analysis.multimodal.train_multimodal \
		--backbone $(BACKBONE) \
		--input-mode $(INPUT_MODE) \
		--fusion-strategy $(FUSION) \
		--use-metabolites \
		--use-augmentation \
		--batch-size 16 \
		--learning-rate 1e-3 \
		--num-epochs-phase1 50 \
		--early-stopping-patience 20 \
		--output-dir analysis/multimodal/outputs_multimodal/$(BACKBONE)_$(INPUT_MODE)_$(FUSION)

# Per-day image study (paper Fig 7-9 replication). Pass extra args via ARGS=.
analysis-paper-perday:
	@echo "===> Per-day image study"
	PYTHONPATH=$(PYTHONPATH) ANALYSIS_OUTPUT_DIR=$(ANALYSIS_OUTPUT_DIR) $(PYTHON) -m analysis.paper_2026_04.perday_image_study $(ARGS)

# BA1+BA2 dataset summary table (paper methods section).
analysis-batch-summary:
	@echo "===> BA1+BA2 descriptive statistics"
	PYTHONPATH=$(PYTHONPATH) ANALYSIS_OUTPUT_DIR=$(ANALYSIS_OUTPUT_DIR) $(PYTHON) -m analysis.paper_2026_04.ba1_ba2_descriptive_stats $(ARGS)

# Verify partner-supplied IDOR organoid list against all_data.json.
analysis-verify-idor:
	@echo "===> Verifying IDOR organoid list against all_data.json"
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m analysis.verify_ba1_ba2_idor_list.verify $(ARGS)

# ====================================
# Pipeline Convenience Targets
# ====================================

pipeline-identifiers: step1

pipeline-mappers: step2 step3 step4

pipeline-preprocessing: step5 step6 step7

# Trains both early and late segmentation models, then runs prediction with each
# on its respective days (early model on Dy03-10, late model on Dy13-30).
# step9-late reads step9-early's output JSON, so order matters.
pipeline-segmentation:
	$(MAKE) step8 PHASE=early
	$(MAKE) step8 PHASE=late
	$(MAKE) step9-early
	$(MAKE) step9-late

pipeline-quality: step10 step11

pipeline-series: step12 step13 step14 step15

pipeline-merge: step16 winsorize-write

pipeline-all: pipeline-identifiers pipeline-mappers pipeline-preprocessing pipeline-segmentation pipeline-quality pipeline-series pipeline-merge
	@echo ""
	@echo "========================================="
	@echo "PREPROCESSING PIPELINE COMPLETE!"
	@echo "========================================="
	@echo "Generated files:"
	@echo "  - $(ALL_DATA_JSON)"
	@echo ""
	@echo "Next steps:"
	@echo "  make train-all              - Train both classifiers"
	@echo ""

train-all: step17 step18
	@echo ""
	@echo "========================================="
	@echo "CLASSIFIER TRAINING COMPLETE!"
	@echo "========================================="
	@echo "Trained models:"
	@echo "  - Image quality classifier: $(IMGQUAL_DIR)/"
	@echo "  - Image survey classifier: $(IMGSURVEY_DIR)/"
	@echo ""

# ====================================
# Validation and Utilities
# ====================================

validate-inputs:
	@echo "===> Validating input files..."
	@if [ ! -f "$(IMAGE_VERIFICATION_CSV)" ]; then \
		echo "ERROR: Image verification CSV not found: $(IMAGE_VERIFICATION_CSV)"; \
		exit 1; \
	fi
	@if [ ! -f "$(SAMPLE_TRACING_XLSX)" ]; then \
		echo "ERROR: Sample tracing Excel not found: $(SAMPLE_TRACING_XLSX)"; \
		exit 1; \
	fi
	@if [ ! -d "$(RAW_IMAGES_DIR)" ]; then \
		echo "ERROR: Raw images directory not found: $(RAW_IMAGES_DIR)"; \
		exit 1; \
	fi
	@if [ ! -d "$(MANUAL_MASKS_DIR)" ]; then \
		echo "ERROR: Manual masks directory not found: $(MANUAL_MASKS_DIR)"; \
		exit 1; \
	fi
	@if [ ! -f "$(METABOLITE_XLSX)" ]; then \
		echo "ERROR: Metabolite Excel not found: $(METABOLITE_XLSX)"; \
		exit 1; \
	fi
	@if [ ! -d "$(SURVEY_DIR)" ]; then \
		echo "ERROR: Survey directory not found: $(SURVEY_DIR)"; \
		exit 1; \
	fi
	@echo "===> All input files validated successfully!"

validate-mmcv-env:
	@if [ ! -x "$(MMCV_ENV_PATH)/bin/nvcc" ]; then \
		echo "ERROR: mmcv_env not found or incomplete at $(MMCV_ENV_PATH)"; \
		echo "  Expected nvcc at $(MMCV_ENV_PATH)/bin/nvcc (provided by cudatoolkit-dev=11.3.1)."; \
		echo "  Create the env with:"; \
		echo "    conda env create -f pipeline/images/segmentation_mmseg/mmcv_env.yaml"; \
		exit 1; \
	fi

clean:
	@echo "Cleaning generated files..."
	@echo "This will remove:"
	@echo "  - $(INTERMEDIATE_DIR)/ (all intermediate data)"
	@echo "  - $(MODELS_DIR)/ (all trained models)"
	@echo "  - $(ALL_DATA_JSON)"
	@echo ""
	@echo "Raw data in $(RAW_DIR)/ will NOT be touched."
	@echo ""
	@read -p "Are you sure? [y/N] " -n 1 -r; \
	echo; \
	if [[ $$REPLY =~ ^[Yy]$$ ]]; then \
		rm -rf $(INTERMEDIATE_DIR)/*; \
		rm -rf $(MODELS_DIR)/*; \
		rm -f $(ALL_DATA_JSON); \
		echo "Cleaned!"; \
	else \
		echo "Cancelled."; \
	fi

# Show current configuration
config:
	@echo "========================================="
	@echo "Current Configuration"
	@echo "========================================="
	@echo "DATA_ROOT          = $(DATA_ROOT)"
	@echo "  RAW_DIR          = $(RAW_DIR)"
	@echo "  INTERMEDIATE_DIR = $(INTERMEDIATE_DIR)"
	@echo "  MODELS_DIR       = $(MODELS_DIR)"
	@echo "  ANALYSIS_OUTPUT  = $(ANALYSIS_OUTPUT_DIR)"
	@echo "PYTHON             = $(PYTHON)"
	@echo "PYTHON_MMCV        = $(PYTHON_MMCV)"
	@echo ""
	@echo "Raw Inputs:"
	@echo "  IMAGE_VERIFICATION_CSV = $(IMAGE_VERIFICATION_CSV)"
	@echo "  SAMPLE_TRACING_XLSX    = $(SAMPLE_TRACING_XLSX)"
	@echo "  RAW_IMAGES_DIR         = $(RAW_IMAGES_DIR)"
	@echo "  MANUAL_MASKS_DIR       = $(MANUAL_MASKS_DIR)"
	@echo "  METABOLITE_XLSX        = $(METABOLITE_XLSX)"
	@echo "  SURVEY_DIR             = $(SURVEY_DIR)"
	@echo ""
	@echo "Intermediate Outputs:"
	@echo "  INDEXES_DIR            = $(INDEXES_DIR)"
	@echo "  ALL_DATA_JSON          = $(ALL_DATA_JSON)"
	@echo ""
	@echo "Model Outputs:"
	@echo "  IMGQUAL_DIR            = $(IMGQUAL_DIR)"
	@echo "  IMGSURVEY_DIR          = $(IMGSURVEY_DIR)"
	@echo "  MMSEG_DIR              = $(MMSEG_DIR)"
	@echo ""
	@echo "Options:"
	@echo "  OVERWRITE          = $(OVERWRITE)"
	@echo "  TARGET_WIDTH       = $(TARGET_WIDTH)"
	@echo "  TARGET_HEIGHT      = $(TARGET_HEIGHT)"
	@echo "  MIN_SURVEY_VOTES   = $(MIN_SURVEY_VOTES)"
	@echo "  DETERMINISTIC      = $(DETERMINISTIC)"
	@echo "  SEED               = $(SEED)"
	@echo ""
